### ISSUE TITLE
.editorconfig

### ISSUE THREAD

**Issue by tregusti** [suhajdab/home-v2#15]
The editorconfig file looks like an example file taken from editorconfig.org. It does not match your file structure.

You seem to be using tabs the width of 4 spaces. I can ensure the config files specifies this, else tell med if you want to use spaces or tabs, and what size.

tabs of size 4 is good for alignment when using `var`:

```js
var ping,
    pong
```

However, I would recommend using spaces of 2 or 4 instead, since not all viewers and editors adjust to the tab width setting making the code look less organized. See:

![](https://dl.dropboxusercontent.com/s/nvn81ltd1nh7z8s/2015-11-01%20at%2019.58.png?dl=0)

Command me!

**Comment by suhajdab** [comment]
Tab size 4 sounds great! :)
